# Generated by Django 3.2.19 on 2023-06-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iq_eq_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testuser",
            name="eq",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="testuser",
            name="iq",
            field=models.IntegerField(null=True),
        ),
    ]
